syntax = "proto3";

package rpc_detail_v0_1;

import "method.proto";

enum MethodType{
	MET_UNKNOW = 0;
	MET_ADD = 1;
	MET_DIV = 2;
	MET_CALC_MATRIX = 3;
}

enum StatusCode {
    STATUS_UNKNOWN = 0;
    STATUS_OK = 1;
    STATUS_BAD_REQUEST = 2;
    STATUS_METHOD_NOT_FOUND = 3;
    STATUS_PARSE_ERROR = 4;
    STATUS_INVOKE_ERROR = 5;
    STATUS_INTERNAL_ERROR = 6;
}

message Request{
	uint64 id = 1;
	MethodType type = 2;
	bytes body = 3; 
}


message Response{
	uint64 id = 1;
	StatusCode status = 2;
	MethodType type = 3;
	bytes body = 4;
	string error_message = 5;
}